name: deploy project

on:
  push:
    branches:
      - 'main'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4
    - name: build image
      run: docker build ./app -t lbrodziak/my-app:latest
    - name: push image
      run: |
        docker login -u lbrodziak -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push lbrodziak/my-app:latest
      
